### ISSUE TITLE
Name of the package

### ISSUE THREAD

**Issue by PetrKryslUCSD** [jlchan/JuliaDG#2]
Neat. Just note that names of packages that incorporate Julia are frowned upon  in general. The language is rather mentioned in the suffix of the name. That makes the Julia packages easier to find, in my experience. For instance https://github.com/JuliaSparse/Metis.jl

**Comment by jlchan** [comment]
That's very good to know, and thanks for the heads up.  It's been renamed to ESDG (energy or entropy stable DG)

**Comment by PetrKryslUCSD** [comment]
Great!

**Comment by PetrKryslUCSD** [comment]
Sorry, I just noticed: that suffix actually might be nice. Makes Julia packages more discoverable. So I would go with ESDG.jl.

**Comment by jlchan** [comment]
Oops - I didn't catch what you meant with the suffix at first.  Fixed now.  Thanks again!
